# Site specific settings
title: "FlawCon"
name: "The FlawCon Patch Notes"
keywords: "security, conference, blog, updates"
baseurl: "/"
url: "https://blob.flawcon.xyz"
description: "Blog for a security conference in Huddersfield"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
#disqus: test
twitter: Flawcon 
#facebook: 
github: Flawcon
#google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
